### PR TITLE
Require NodeJS 4.x LTS

### PR DESCRIPTION
**Pull request by kristerkari**
Same as https://github.com/stylelint/stylelint/pull/1594 + changed Node.js version from 5 to 6 in .travis.yml

### CODE REVIEW

**Comment by dryoma** [comment]
How about adding a line to the Readme, maybe explaining stylelint dependency?

**Comment by kristerkari** [comment]
> How about adding a line to the Readme, maybe explaining stylelint dependency?

Sure. What should it say?

**Comment by kristerkari** [comment]
I'll merge this without the README change, we can add that later.

**Comment by dryoma** [comment]
Sure. Sorry, didn't have a minute to give it a proper thought.

**Comment by kristerkari** [comment]
No worries! I'm not in a hurry :)

**Comment by dryoma** [comment]
Added a note to readme.

**Pull request merged**
