### PR TITLE
Switch to GitHub Actions CI.

### LINKED ISSUE #398: Switch to GitHub Actions
I'll take a stab at it later

### PR DESCRIPTION
**Pull request by XhmikosR**
Preview: <https://github.com/XhmikosR/stylelint-scss/runs/308215912>

Fixes #398, closes #408

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kristerkari before you merge this please remove any Travis CI and AppVeyor instances from the repo apps/hooks/integrations.

We could probably improve this later, like running lint only once.

**Comment by kristerkari** [comment]
Thanks!

> before you merge this please remove any Travis CI and AppVeyor instances from the repo apps/hooks/integrations.

Yeah I need to remember that this time.

**Comment by kristerkari** [comment]
@XhmikosR can you update your branch now with for example `git commit --amend` and do a force push?

**Comment by kristerkari** [comment]
I have disabled Travis & AppVeyor

**Comment by XhmikosR** [comment]
Give me a few minutes to rebase, but you can always protect the master branch and thus check the option for the branches to be up to date. This will give you a button.

**Comment by XhmikosR** [comment]
Done https://github.com/XhmikosR/stylelint-scss/runs/310166195

**Pull request merged**
