### PR TITLE
Prepare version 1.0.0

### PR DESCRIPTION
**Pull request by kristerkari**
Prepare version 1.0.0. 

I have released a "pre-release" if you want to test it out, just `npm i stylelint-scss@0.0.0-alpha.1`.

ping @davidtheclark @jeddy3 @dryoma Let me know if there is anything that should be fixed before this plugin goes live.

### CODE REVIEW

**Comment by dryoma** [comment]
I could only come up with adding `"prebuild": "rimraf dist",` to `"scripts"` (yet I'm not it is used in installing from NPM, more likely it's for Travis CI and other CIs).

**Comment by kristerkari** [comment]
Ah true, I need to do that.

**Comment by davidtheclark** [comment]
You got the namespace in there, so looks good.

**Comment by kristerkari** [comment]
Anything else, or should we go ahead and release?

**Pull request merged**
