### PR TITLE
Added rule for dollar-variable-first-in-block

### PR DESCRIPTION
**Pull request by larsmunkholm**
This adds a `dollar-variable-first-in-block` rule that checks if variables are put first in a block (root and rules).

It can be set to ignore comments and imports, and make exceptions when variables are placed in root or inside an at-rule, function, mixin, if/else or for/each/while-loops.

This is my first contribution to `stylelint-scss` ... Please don't hesitate to let me know, if I'm doing anything wrong :)

### CODE REVIEW

**Comment by kristerkari** [comment]
I'm really sorry that I have not reviewed this and the other PR yet (been busy). I'll have a look at them when I can.

**Comment by larsmunkholm** [comment]
No worries :) I'm not in a hurry

**Comment by DonGissel** [comment]
This looks pretty neat!

**Comment by larsmunkholm** [comment]
Should I give up on this? 😅

**Comment by kristerkari** [comment]
> Should I give up on this?

No! Sorry that it took me so long :)

**Pull request merged**
