### PR TITLE
Add `at-least-one-space` opt to space after var colon rule (closes #195)

### LINKED ISSUE #195: dollar-variable-colon-space-after: At least one space
Would it be complex to add the possibility of having at least one space after the colon, for the purpose of aligning values ?
```
$base-color:     #ff0000;
$primary-color:  #00ff00;
$alt-color:      #0000ff;
```
Ref: [SCSS Lint at_least_one_space](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceaftervariablecolon)

### PR DESCRIPTION
**Pull request by stormwarning**
~🚧 A work-in-progress — still need to add tests.~

Should address #195 

I think this should be ready; let me know what you think!

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks a lot! I don't have my computer with me right now, but I'll review this as soon as I can.

**Comment by stormwarning** [comment]
Thanks! The two "Update Prettier formatting" commits can be ignored — I committed formatting changes separately out of habit, before realising there was a hook to update the formatting anyway. 🤷‍♂️

**Comment by kristerkari** [comment]
Looks really good. Would it be possible for you to also update the `README` file of the rule to mention the option?

**Comment by kristerkari** [comment]
and I'm ok with ignoring `package.json` and `package-lock.json` formatting. Running `npm install` will format them anyway, so there's less noise if we don't format them with Prettier.

**Comment by kristerkari** [comment]
Thanks a lot! I think that this is good to go now. 👍 

I'll see if I manage to release a new version tomorrow with this and a bugfix to another rule.

**Pull request merged**
