### PR TITLE
Plugin interface, readme, changelog

### PR DESCRIPTION
**Pull request by dryoma**
Implements items 3-7 from #14

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks! I'll try to get this reviewed tonight.

**Comment by kristerkari** [comment]
I tested this against my own project and everything was working correctly. Good job!

I'll merge this so we can start preparing the release of v1.0. 👍

**Comment by dryoma** [comment]
Great. And thanks for a Collab permission! hope to prove to be useful :)

**Comment by kristerkari** [comment]
> thanks for a Collab permission! hope to prove to be useful :)

No problem, I'm usually quite busy and I don't have time to do everything myself :)

**Pull request merged**
