### PR TITLE
selector-no-union-class-name: fix false positives for id/attr/pseudo

### LINKED ISSUE #341: `selector-no-union-class-name` rule false positive
The `selector-no-union-class-name` rule thinks there are errors here:

```scss
.icon {
  &:last-child { // Error on this line
    margin-left: 0.75rem;
  }

  &#divID { // Error on this line
    margin-left: 0.75rem;
  }
}
```

It seems the rule doesn't realize that pseudo-element selectors and ID selectors aren't class name unions.

cc @pipopotamasu

### PR DESCRIPTION
**Pull request by kristerkari**
Fixes #341

@nwoltman @pipopotamasu

### CODE REVIEW

**Comment by nwoltman** [comment]
This looks like it'll cover all the false positives in my codebase 👍

**Comment by kristerkari** [comment]
Thanks for having a look, I think that this fix is good to go then!

**Comment by mpg-yamato-murakami** [comment]
thx!

**Comment by pipopotamasu** [comment]
thx!

**Pull request merged**
