### PR TITLE
operator-no-unspaced: fix signed parameter in a function call inside …

### PR DESCRIPTION
**Pull request by airyboy**
fix signed parameter in a function call inside interpolation

fixes bug https://github.com/kristerkari/stylelint-scss/issues/450

### CODE REVIEW

**Comment by kristerkari** [comment]
Looks great! Thanks

**Comment by kristerkari** [comment]
@airyboy Looks like you are using your fork's master branch for the changes, and it's including the changes from `comment-no-empty` to this pull request too. Would it be possible for you to use branches for your changes instead of master?

**Comment by airyboy** [comment]
@kristerkari sure, sorry, I haven't been using github for a while

**Comment by airyboy** [comment]
I created PR #465, this PR should be closed

**Pull request closed without merging**
