### PR TITLE
Fix failing partial-no-import test

### PR DESCRIPTION
**Pull request by kristerkari**
This fixes a test that is currently failing on master branch. 

ping @dryoma

### CODE REVIEW

**Comment by dryoma** [comment]
Hmm, that's strange. Everything is ok on my side. Maybe it has something to do with whether it's windows/linux and the slashes used?

**Comment by kristerkari** [comment]
> Hmm, that's strange. Everything is ok on my side. Maybe it has something to do with whether it's windows/linux and the slashes used (I use Windows)?

That might be, I'm using osx and it is also failing on my machine.

**Comment by dryoma** [comment]
The problem was in hard-coded path slashes I used to test dirs starting with `_`. I'm afraid `if (/\\/.test(fileName)) { return }` won't help here.

I pushed a fix in #73

**Comment by kristerkari** [comment]
ok, thanks! Let's close this then.

**Pull request closed without merging**
