### PR TITLE
If else newlines

### PR DESCRIPTION
**Pull request by dryoma**
Implements #82 

These rules with the corresponding options are added (the reasoning and examples are in the issue discussion):
```
"at-if-closing-brace-newline-after": "always-last-in-chain"
"at-if-closing-brace-space-after": "always-intermediate"|"never-intermediate"
"at-else-closing-brace-newline-after": "always-last-in-chain"
"at-else-closing-brace-space-after": "always-intermediate"|"never-intermediate"
"at-else-empty-line-before": "never"
```

I also added the /docs folder, for now it only has [examples/if-else.md](https://github.com/kristerkari/stylelint-scss/blob/if-else-newlines/docs/examples/if-else.md).

There are still cases I belive are unresolved:

- [ ] We can't force `@else if` to always be on the same line. Can be solved by the `never` option to [`at-rule-name-newline-after`](http://stylelint.io/user-guide/rules/at-rule-name-newline-after/) (I'm ok with pushing a PR).
- [x] Disallow an empty line before @else when `at-rule-empty-line-before` has `ignoreAtRules: [ "else" ]`.

@ntwb Please see if the functionality that is complete so far works for you, and if there are any other things we need done.

cc. @kristerkari @jeddy3

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks for this, I'll try to find some time to go through the code tonight or tomorrow.

**Comment by ntwb** [comment]
Super weird, I've not been getting notifications for this issue or PR, I'll try to look at it later today 👍

**Comment by kristerkari** [comment]
I went through the code and looks good to me. 👍  Also, it probably makes sense to add "never" option to `at-rule-name-newline-after` if there is no specific reason why that rule can't have that option :)

**Comment by dryoma** [comment]
Added `at-else-empty-line-before` rule so that we could pass this:
```scss
a { ... }

@if {
  // ...
}
@else {
  // ...
}
```

but not this:
```scss
@if {
  // ...
}

@else {
  // ...
}
```
(see the updated second example [here](https://github.com/kristerkari/stylelint-scss/blob/if-else-newlines/docs/examples/if-else.md))

**Comment by dryoma** [comment]
Turns out that `at-rule-name-newline-after: "never"` will force the code to be 
```scss
@elseif () {}
```
due to how `whitespaceChedker` util works (`always-` options require either a space or a newline depending on a corresponding param, and `never-` options disallow whitespace altogether).

So for merging this as is for now. Will add a standalone rule for `@else` if users ask for it.

**Pull request merged**
